version: '3.8'

services:
  angular:
    build: ./app_admin
    ports:
      - "4200:4200"
    volumes:
      - ./app_admin:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run start

  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run start